# Generated by Django 4.2.5 on 2023-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='order_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='order_take',
            field=models.DateField(blank=True, null=True),
        ),
    ]
