# Generated by Django 4.2.5 on 2023-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0002_requestaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='request_access',
            field=models.BooleanField(default=False),
        ),
    ]
