# Generated by Django 4.2.5 on 2023-09-30 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailer', '0002_tailor_order_deadline_tailor_order_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
