# Generated by Django 4.2.5 on 2023-10-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0004_alter_tailor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
