# Generated by Django 4.2.5 on 2023-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0004_remove_requestaccess_user_requestaccess_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
