# Generated by Django 4.2.5 on 2023-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0005_customer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestaccess',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
