# Generated by Django 4.2.5 on 2023-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0006_tailor_arm_hole_tailor_collar_tailor_cuff_tailor_hip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
