# Generated by Django 4.2.5 on 2023-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0007_alter_tailor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='extra_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
