# Generated by Django 4.2.5 on 2023-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0007_customer_tailer_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cloth_quantites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cloth_types',
            field=models.CharField(blank=True, choices=[('Cotton', 'Cotton'), ('Fabric', 'Fabric'), ('Silk', 'Silk'), ('Linen', 'Linen')], max_length=255, null=True),
        ),
    ]
