# Generated by Django 4.2.5 on 2023-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0008_customer_cloth_quantites_customer_cloth_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Ready', 'Ready')], max_length=255, null=True),
        ),
    ]
