# Generated by Django 4.2.5 on 2023-10-22 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailer', '0008_tailor_extra_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tailor',
            new_name='Customer',
        ),
    ]
