# Generated by Django 4.2.5 on 2023-11-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0009_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Ready', 'Ready')], default='Waiting', max_length=255, null=True),
        ),
    ]
