# Generated by Django 4.2.5 on 2023-11-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0010_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pant_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pant_width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
