# Generated by Django 4.2.5 on 2023-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0010_customer_payment_customer_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
