# Generated by Django 4.2.5 on 2023-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailer', '0011_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
